server:  port: 8022

spring:
  data:
    mongodb:
      database: dbhospedajeweb
      port: 27017
      host: localhost
      username: marco
      password: marco
url:  bungalow:   host: http://localhost:8014/bungalow  ingreso:   host: http://localhost:8017/ingreso    